name: Build Project

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  
jobs:
  Release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Build
        shell: bash
        run: '"/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe" -property:Configuration=Release'
      
      - name: Upload Artifact
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v2.2.1
        with:
          name: Release
          path: |
            ./Release/V21.dll
  
  Notification:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: [Release]
    steps:
      - name: Discord Notification
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: info
          description: "Project Build"
          details: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          webhookUrl: ${{ secrets.DISCORD_BUILD_WEBHOOK }}
