name: Build Project

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  
jobs:
  Release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name:  Config
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run:   echo ::set-env name=DXSDK_DIR::$HOME/cache/
        shell: bash
      
      - name: Cache
        id:   cache
        uses: actions/cache@v1
        with:
          path: ~/cache
          key:  cache

      - name:  Cache create
        if:    steps.cache.outputs.cache-hit != 'true'
        run:   |
          curl -L https://dl.filehorse.com/win/developer-tools/directx-sdk/DXSDK_Jun10.exe?st=iL8Rwjm3vMrk_d3uhCNhuw&e=1612822986&fn=DXSDK_Jun10.exe -o _DX2010_.exe
          7z x _DX2010_.exe DXSDK/Include -o_DX2010_
          7z x _DX2010_.exe DXSDK/Lib/x86 -o_DX2010_
          mv _DX2010_/DXSDK $HOME/cache
          rm -fR _DX*_ _DX*_.exe
        shell: bash


      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1
      
      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        # Add additional options to the MSBuild command line here (like platform or verbosity level).
        # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
        run: msbuild /m /p:Configuration="Release"
      
      - name: Upload Artifact
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v2.2.1
        with:
          name: Release
          path: |
            ./Release/V21.dll
  
  Notification:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: [Release]
    steps:
      - name: Discord Notification
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: info
          description: "Project Build"
          details: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          webhookUrl: ${{ secrets.DISCORD_BUILD_WEBHOOK }}
